#' Write code for server.R
#'
#' @rdname wrSVlib
#' @export wrSVlib
#'
wrSVlib <- function() {
  glue::glue(
    'library(shiny) \n',
    'library(shinyhelper) \n',
    'library(data.table) \n',
    'library(Matrix) \n',
    'library(DT) \n',
    'library(magrittr) \n',
    'library(ggplot2) \n',
    'library(ggrepel) \n',
    'library(hdf5r) \n',
    'library(ggdendro) \n',
    'library(grid) \n',
    'library(gridExtra) \n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVload
#' @export wrSVload
#'
wrSVload <- function(prefix) {
  glue::glue(
    '{prefix}conf = readRDS("./{prefix}conf.rds")\n',
    '{prefix}meta = readRDS("./{prefix}meta.rds")\n',
    '{prefix}gene = readRDS("./{prefix}gene.rds")\n',
    '{prefix}dimr = readRDS("./{prefix}dimr.rds")\n',
    '{prefix}def  = readRDS("./{prefix}def.rds")\n',
    '\n'
  )
}

#' Write code for ui.R
#'
#' @rdname wrSVloadS1
#' @export wrSVloadS1
#'
wrSVloadS1 <- function(prefix) {
  glue::glue(
    '{prefix}image = readRDS("./{prefix}image.rds")\n',
    '\n'
  )
}

#' Write code for ui.R
#'
#' @rdname wrSVloadT1
#' @export wrSVloadT1
#'
wrSVloadT1 <- function(prefix) {
  glue::glue(
    '{prefix}bw   = readRDS("./{prefix}bw.rds")\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVpre
#' @export wrSVpre
#'
wrSVpre <- function() {
  glue::glue(
    'source("./shinyFunc.R")\n',
    'pdf(file = NULL)\n',
    '\n',
    '\n',
    '\n',
    '### Useful stuff \n',
    '# Colour palette \n',
    'cList = list(c("grey85","#FFF7EC","#FEE8C8","#FDD49E","#FDBB84", \n',
    '               "#FC8D59","#EF6548","#D7301F","#B30000","#7F0000"), \n',
    '             c("#4575B4","#74ADD1","#ABD9E9","#E0F3F8","#FFFFBF", \n',
    '               "#FEE090","#FDAE61","#F46D43","#D73027")[c(1,1:9,9)], \n',
    '             c("#FDE725","#AADC32","#5DC863","#27AD81","#21908C", \n',
    '               "#2C728E","#3B528B","#472D7B","#440154")) \n',
    'names(cList) = c("White-Red", "Blue-Yellow-Red", "Yellow-Green-Purple") \n',
    '\n',
    '# Panel sizes \n',
    'pList = c("400px", "600px", "800px") \n',
    'names(pList) = c("Small", "Medium", "Large") \n',
    'pList2 = c("500px", "700px", "900px") \n',
    'names(pList2) = c("Small", "Medium", "Large") \n',
    'pList3 = c("600px", "800px", "1000px") \n',
    'names(pList3) = c("Small", "Medium", "Large") \n',
    'sList = c(18,24,30)\n',
    'names(sList) = c("Small", "Medium", "Large") \n',
    '\n',
    '\n',
    '\n',
    '### Start server code \n',
    'shinyServer(function(input, output, session) {{ \n',
    '  ### For all tags and Server-side selectize \n',
    '  observe_helpers() \n',
    '  optCrt="{{ option_create: function(data,escape) {{return(\'<div class=\\"create\\"><strong>\' + \'</strong></div>\');}} }}" \n', 
    '  observe({{ \n', 
    '    invalidateLater(30000) # ping every 30 seconds to keep connection alive \n', 
    '    cat(".") \n', 
    '  }}) \n', 
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainA1
#' @export wrSVmainA1
#'
wrSVmainA1 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab A1 \n',
    '  getG{prefix}a1inp1 <- reactive({{ \n',
    '    req(gsub("^Assay: ", "", input${prefix}a1ass1)) \n',
    '    if(gsub("^Assay: ", "", input${prefix}a1ass1) == "Cell Information"){{ \n',
    '      res <- {prefix}conf$UI \n',
    '      resDef <- {prefix}def$meta1 \n',
    '      resLen <- length(res) \n',
    '    }} else {{ \n',
    '      res <- names({prefix}gene[[gsub("^Assay: ", "", input${prefix}a1ass1)]]) \n',
    '      resDef <- {prefix}def$gene1[[gsub("^Assay: ", "", input${prefix}a1ass1)]] \n',
    '      resLen <- 7 \n',
    '    }} \n',
    '    return(list(res,resDef,resLen))\n',
    '  }})\n',
    '  observeEvent(gsub("^Assay: ", "", input${prefix}a1ass1), {{\n',
    '    updateSelectizeInput(session, "{prefix}a1inp1", choices = getG{prefix}a1inp1()[[1]], \n',
    '                         server = TRUE, selected = getG{prefix}a1inp1()[[2]], options = list( \n',
    '                           maxOptions = getG{prefix}a1inp1()[[3]], create = TRUE, \n',
    '                           persist = TRUE, render = I(optCrt))) \n',
    '  }})\n',
    '  output${prefix}a1sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a1sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}a1sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a1sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a1sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}a1sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a1sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a1sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}a1sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}a1sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}a1sub3) || input${prefix}a1sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a1sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}a1sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}a1sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}a1sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a1sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a1sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}a1sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a1sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a1sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}a1sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  \n',
    '  {prefix}a1oup1xy <- reactiveValues(x = NULL, y = NULL)\n',
    '  observe({{\n',
    '    brush <- input${prefix}a1inp1.br\n',
    '    if (!is.null(brush)) {{\n',
    '      xrange <- range({prefix}dimr[[input${prefix}a1dr]][, 1], na.rm = TRUE)\n',
    '      yrange <- range({prefix}dimr[[input${prefix}a1dr]][, 2], na.rm = TRUE)\n',
    '      {prefix}a1oup1xy$x <- c(brush$xmin * diff(xrange) + xrange[1],\n',
    '                              brush$xmax * diff(xrange) + xrange[1])\n',
    '      {prefix}a1oup1xy$y <- c(brush$ymin * diff(yrange) + yrange[1],\n',
    '                              brush$ymax * diff(yrange) + yrange[1])\n',
    '    }} else {{\n',
    '      {prefix}a1oup1xy$x <- NULL; {prefix}a1oup1xy$y <- NULL\n',
    '    }}\n',
    '  }})\n',
    '  {prefix}a1oup1br <- reactive({{\n',
    '    req(input${prefix}a1inp1, cancelOutput = TRUE)\n',
    '    req(nchar(input${prefix}a1inp1) > 0, cancelOutput = TRUE)\n',
    '    sc2Ddimr({prefix}conf, {prefix}meta, {prefix}dimr, input${prefix}a1dr, input${prefix}a1inp1,\n',
    '             "{prefix}assay_", {prefix}gene, input${prefix}a1ass1, input${prefix}a1sub1, input${prefix}a1sub2,  \n',
    '             input${prefix}a1sub3, input${prefix}a1sub4,\n',
    '             input${prefix}a1min1, input${prefix}a1max1, input${prefix}a1siz/2, input${prefix}a1ord1,\n',
    '             cList[[input${prefix}a1col1]], sList[input${prefix}a1fsz]/2, \n',
    '             input${prefix}a1asp, FALSE, FALSE) \n',
    '  }})\n',
    '  output${prefix}a1oup1.br <- renderPlot({{{prefix}a1oup1br() + theme(legend.position = "none")}}) \n',
    '  \n',
    '  {prefix}a1oup1 <- reactive({{\n',
    '    req(input${prefix}a1inp1, cancelOutput = TRUE)\n',
    '    req(nchar(input${prefix}a1inp1) > 0, cancelOutput = TRUE)\n',
    '    sc2Ddimr({prefix}conf, {prefix}meta, {prefix}dimr, input${prefix}a1dr, input${prefix}a1inp1,\n',
    '             "{prefix}assay_", {prefix}gene, input${prefix}a1ass1, input${prefix}a1sub1, input${prefix}a1sub2,  \n',
    '             input${prefix}a1sub3, input${prefix}a1sub4,\n',
    '             input${prefix}a1min1, input${prefix}a1max1, input${prefix}a1siz, input${prefix}a1ord1,\n',
    '             cList[[input${prefix}a1col1]], sList[input${prefix}a1fsz], \n',
    '             input${prefix}a1asp, input${prefix}a1txt, input${prefix}a1lab1)\n',
    '  }})\n',
    '  output${prefix}a1oup1 <- renderPlot({{\n',
    '    if(is.null({prefix}a1oup1xy$x[1])){{\n',
    '      {prefix}a1oup1() + theme(legend.position = "none")\n',
    '    }} else {{\n',
    '      {prefix}a1oup1() + theme(legend.position = "none") + \n',
    '        scale_x_continuous(limits = {prefix}a1oup1xy$x, expand = c(0, 0)) + \n',
    '        scale_y_continuous(limits = {prefix}a1oup1xy$y, expand = c(0, 0)) \n',
    '    }}\n',
    '  }})\n',
    '  output${prefix}a1oup1.ui <- renderUI({{plotOutput("{prefix}a1oup1", height = pList[input${prefix}a1psz])}})\n',
    '  output${prefix}a1oup1.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a1dr,"_",input${prefix}a1inp1,".",input${prefix}a1oup1.f) }},\n',
    '    content = function(file) {{ \n',
    '      if(is.null({prefix}a1oup1xy$x[1])){{\n',
    '        ggsav(file, height = input${prefix}a1oup1.h, width = input${prefix}a1oup1.w, \n',
    '              plot = {prefix}a1oup1() + theme(legend.position = "none"))\n',
    '      }} else {{\n',
    '        ggsav(file, height = input${prefix}a1oup1.h, width = input${prefix}a1oup1.w, \n',
    '              plot = {prefix}a1oup1() + theme(legend.position = "none") + \n',
    '                scale_x_continuous(limits = {prefix}a1oup1xy$x, expand = c(0, 0)) + \n',
    '                scale_y_continuous(limits = {prefix}a1oup1xy$y, expand = c(0, 0)))\n',
    '      }}\n',
    '  }})\n',
    '  output${prefix}a1oup3 <- renderPlot({{grid.newpage(); grid.draw(g_legend({prefix}a1oup1()))}})\n',
    '  output${prefix}a1oup3.ui <- renderUI({{plotOutput("{prefix}a1oup3", height = 72*convertHeight(\n',
    '    grobHeight(g_legend({prefix}a1oup1())), unitTo="in", valueOnly=TRUE) + 50)}})\n',
    '  output${prefix}a1oup3.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a1dr,"_",input${prefix}a1inp1,"_leg.",input${prefix}a1oup3.f) }},\n',
    '    content = function(file) {{ \n',
    '      grid.newpage(); grid.draw(g_legend({prefix}a1oup1()))\n',
    '      ggsav(file, height = input${prefix}a1oup3.h, width = input${prefix}a1oup3.w, plot = grid.grab())\n',
    '  }}) \n',
    '  \n',
    '  output${prefix}a1.dt <- renderDataTable({{\n',
    '    ggData = sc2Dnum({prefix}conf, {prefix}meta, {prefix}dimr, input${prefix}a1dr, {prefix}a1oup1xy$x, {prefix}a1oup1xy$y, input${prefix}a1inp1,\n',
    '                     "{prefix}assay_", {prefix}gene, input${prefix}a1ass1, input${prefix}a1sub1, input${prefix}a1sub2, input${prefix}a1sub3, input${prefix}a1sub4, input${prefix}a1splt)\n',
    '    datatable(ggData, rownames = FALSE, extensions = "Buttons",\n',
    '              options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>%\n',
    '      formatRound(columns = c("pctZoom"), digits = 2)\n',
    '  }})\n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainS3
#' @export wrSVmainS3
#'
wrSVmainS3 <- function(prefix) {
  glue::glue(
    '  ##############################\n',
    '  # s3 tab dynamic html events #\n',
    '  ##############################\n',
    '  getG{prefix}s3inp1 <- reactive({{\n',
    '    req(input${prefix}s3ass1)\n',
    '    res <- names({prefix}gene[[input${prefix}s3ass1]])\n',
    '    resDef1 <- {prefix}def$gene1[[input${prefix}s3ass1]]\n',
    '    return(list(res, resDef1))\n',
    '  }})\n',
    '\n',
    '  observeEvent(input${prefix}s3ass1, {{\n',
    '    updateSelectizeInput(\n',
    '      session,\n',
    '      "{prefix}s3feat1",\n',
    '      choices = getG{prefix}s3inp1()[[1]],\n',
    '      server = TRUE,\n',
    '      selected = getG{prefix}s3inp1()[[2]],\n',
    '      options = list(\n',
    '        maxOptions = 7, create = FALSE, persist = TRUE, render = I(optCrt)\n',
    '      )\n',
    '    )\n',
    '  }})\n',
    '  \n',
    '  output${prefix}s3sub1.ui <- renderUI({{\n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s3sub1]$fID, "\\\\|")[[1]]\n',
    '    checkboxGroupInput("{prefix}s3sub2", "Select which cells to show",\n',
    '      inline = TRUE,\n',
    '      choices = sub, selected = sub\n',
    '    )\n',
    '  }})\n',
    '  observeEvent(input${prefix}s3sub1non, {{\n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s3sub1]$fID, "\\\\|")[[1]]\n',
    '    updateCheckboxGroupInput(session,\n',
    '      inputId = "{prefix}s3sub2", label = "Select which cells to show",\n',
    '      choices = sub, selected = NULL, inline = TRUE\n',
    '    )\n',
    '  }})\n',
    '  observeEvent(input${prefix}s3sub1all, {{\n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s3sub1]$fID, "\\\\|")[[1]]\n',
    '    updateCheckboxGroupInput(session,\n',
    '      inputId = "{prefix}s3sub2", label = "Select which cells to show",\n',
    '      choices = sub, selected = sub, inline = TRUE\n',
    '    )\n',
    '  }})\n',
    '  output${prefix}s3sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}s3sub3) || input${prefix}s3sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s3sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}s3sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}s3sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}s3sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s3sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s3sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}s3sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s3sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s3sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}s3sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  \n',
    '  #########################\n',
    '  # s3 tab static outputs #\n',
    '  #########################\n',
    '  output${prefix}s3oup1 <- renderPlot({{\n',
    '    scDRcellsplit(\n',
    '      {prefix}conf,\n',
    '      {prefix}meta,\n',
    '      {prefix}def,\n',
    '      {prefix}dimr,\n',
    '      {prefix}gene,\n',
    '      paste0("{prefix}assay_", input${prefix}s3ass1, ".h5"),\n',
    '      input${prefix}s3ass1,\n',
    '      input${prefix}s3dr,\n',
    '      input${prefix}s3feat1,\n',
    '      input${prefix}s3inp3,\n',
    '      input${prefix}s3txt,\n',
    '      input${prefix}s3fsz,\n',
    '      input${prefix}s3siz,\n',
    '      input${prefix}s3asp,\n',
    '      input${prefix}s3col1,\n',
    '      input${prefix}s3ord1,\n',
    '      input${prefix}s3sub1,\n',
    '      input${prefix}s3sub2\n',
    '    )\n',
    '  }})\n',
    '  \n',
    '  output${prefix}s3oup1.ui <- renderUI({{\n',
    '    plotOutput("{prefix}s3oup1", height = pList[input${prefix}s3psz])\n',
    '  }})\n',
    '  \n',
    '  output${prefix}s3oup1.pdf <- downloadHandler(\n',
    '    filename = function() {{\n',
    '      paste0(\n',
    '        "{prefix}", input${prefix}s3drX, "_", input${prefix}s3drY, "_",\n',
    '        input${prefix}s3inp1, ".pdf"\n',
    '      )\n',
    '    }},\n',
    '    content = function(file) {{\n',
    '      ggsave(\n',
    '        file,\n',
    '        device = "pdf", height = input${prefix}s3oup1.h, width = input${prefix}s3oup1.w, useDingbats = FALSE,\n',
    '        plot = scDRcellsplit(\n',
    '          {prefix}conf,\n',
    '          {prefix}meta,\n',
    '          {prefix}def,\n',
    '          {prefix}dimr,\n',
    '          {prefix}gene,\n',
    '          paste0("{prefix}assay_", input${prefix}s3ass1, ".h5"),\n',
    '          input${prefix}s3ass1,\n',
    '          input${prefix}s3dr,\n',
    '          input${prefix}s3feat1,\n',
    '          input${prefix}s3inp3,\n',
    '          input${prefix}s3txt,\n',
    '          input${prefix}s3fsz,\n',
    '          input${prefix}s3siz,\n',
    '          input${prefix}s3asp,\n',
    '          input${prefix}s3col1,\n',
    '          input${prefix}s3ord1,\n',
    '          input${prefix}s3sub1,\n',
    '          input${prefix}s3sub2\n',
    '        )\n',
    '      )\n',
    '    }}\n',
    '  )\n',
    '  output${prefix}s3oup1.png <- downloadHandler(\n',
    '    filename = function() {{\n',
    '      paste0(\n',
    '        "{prefix}", input${prefix}s3drX, "_", input${prefix}s3drY, "_",\n',
    '        input${prefix}s3inp1, ".png"\n',
    '      )\n',
    '    }},\n',
    '    content = function(file) {{\n',
    '    ggsave(\n',
    '      file,\n',
    '      device = "png", height = input${prefix}s3oup1.h, width = input${prefix}s3oup1.w,\n',
    '      plot = scDRcellsplit(\n',
    '        {prefix}conf,\n',
    '        {prefix}meta,\n',
    '        {prefix}def,\n',
    '        {prefix}dimr,\n',
    '        {prefix}gene,\n',
    '        paste0("{prefix}assay_", input${prefix}s3ass1, ".h5"),\n',
    '        input${prefix}s3ass1,\n',
    '        input${prefix}s3dr,\n',
    '        input${prefix}s3feat1,\n',
    '        input${prefix}s3inp3,\n',
    '        input${prefix}s3txt,\n',
    '        input${prefix}s3fsz,\n',
    '        input${prefix}s3siz,\n',
    '        input${prefix}s3asp,\n',
    '        input${prefix}s3col1,\n',
    '        input${prefix}s3ord1,\n',
    '        input${prefix}s3sub1,\n',
    '        input${prefix}s3sub2\n',
    '      )\n',
    '    )\n',
    '  }}\n',
    ')\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainA2
#' @export wrSVmainA2
#'
wrSVmainA2 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab A2 \n',
    '  getG{prefix}a2inp1 <- reactive({{ \n',
    '    req(gsub("^Assay: ", "", input${prefix}a2ass1)) \n',
    '    if(gsub("^Assay: ", "", input${prefix}a2ass1) == "Cell Information"){{ \n',
    '      res <- {prefix}conf$UI \n',
    '      resDef <- {prefix}def$meta1 \n',
    '      resLen <- length(res) \n',
    '    }} else {{ \n',
    '      res <- names({prefix}gene[[gsub("^Assay: ", "", input${prefix}a2ass1)]]) \n',
    '      resDef <- {prefix}def$gene1[[gsub("^Assay: ", "", input${prefix}a2ass1)]] \n',
    '      resLen <- 7 \n',
    '    }} \n',
    '    return(list(res,resDef,resLen))\n',
    '  }})\n',
    '  observeEvent(gsub("^Assay: ", "", input${prefix}a2ass1), {{\n',
    '    updateSelectizeInput(session, "{prefix}a2inp1", choices = getG{prefix}a2inp1()[[1]], \n',
    '                         server = TRUE, selected = getG{prefix}a2inp1()[[2]], options = list( \n',
    '                           maxOptions = getG{prefix}a2inp1()[[3]], create = TRUE, \n',
    '                           persist = TRUE, render = I(optCrt))) \n',
    '  }})\n',
    '  getG{prefix}a2inp2 <- reactive({{ \n',
    '    req(gsub("^Assay: ", "", input${prefix}a2ass2)) \n',
    '    if(gsub("^Assay: ", "", input${prefix}a2ass2) == "Cell Information"){{ \n',
    '      res <- {prefix}conf$UI \n',
    '      resDef <- {prefix}def$meta1 \n',
    '      resLen <- length(res) \n',
    '    }} else {{ \n',
    '      res <- names({prefix}gene[[gsub("^Assay: ", "", input${prefix}a2ass2)]]) \n',
    '      resDef <- {prefix}def$gene1[[gsub("^Assay: ", "", input${prefix}a2ass2)]] \n',
    '      resLen <- 7 \n',
    '    }} \n',
    '    return(list(res,resDef,resLen))\n',
    '  }})\n',
    '  observeEvent(gsub("^Assay: ", "", input${prefix}a2ass2), {{\n',
    '    updateSelectizeInput(session, "{prefix}a2inp2", choices = getG{prefix}a2inp2()[[1]], \n',
    '                         server = TRUE, selected = getG{prefix}a2inp2()[[2]], options = list( \n',
    '                           maxOptions = getG{prefix}a2inp2()[[3]], create = TRUE, \n',
    '                           persist = TRUE, render = I(optCrt))) \n',
    '  }})\n',
    '    output${prefix}a2sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a2sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}a2sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a2sub1non, {{\n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a2sub1]$fID, "\\\\|")[[1]]\n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}a2sub2", label = "Select which cells to show",\n',
    '                             choices = sub, selected = NULL, inline = TRUE)\n',
    '  }})\n',
    '  observeEvent(input${prefix}a2sub1all, {{\n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a2sub1]$fID, "\\\\|")[[1]]\n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}a2sub2", label = "Select which cells to show",\n',
    '                             choices = sub, selected = sub, inline = TRUE)\n',
    '  }})\n',
    '  output${prefix}a2sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}a2sub3) || input${prefix}a2sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a2sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}a2sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}a2sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}a2sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a2sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a2sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}a2sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a2sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a2sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}a2sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  \n',
    '  {prefix}a2oup1 <- reactive({{\n',
    '    sc2Ddimr({prefix}conf, {prefix}meta, {prefix}dimr, input${prefix}a2dr, input${prefix}a2inp1,\n',
    '             "{prefix}assay_", {prefix}gene, input${prefix}a2ass1, input${prefix}a2sub1, input${prefix}a2sub2,  \n',
    '             input${prefix}a2sub3, input${prefix}a2sub4,\n',
    '             input${prefix}a2min1, input${prefix}a2max1, input${prefix}a2siz, input${prefix}a2ord1,\n',
    '             cList[[input${prefix}a2col1]], sList[input${prefix}a2fsz], \n',
    '             input${prefix}a2asp, input${prefix}a2txt, input${prefix}a2lab1) \n',
    '  }})\n',
    '  output${prefix}a2oup1 <- renderPlot({{{prefix}a2oup1() + theme(legend.position = "none")}})\n',
    '  output${prefix}a2oup1.ui <- renderUI({{plotOutput("{prefix}a2oup1", height = pList[input${prefix}a2psz])}})\n',
    '  output${prefix}a2oup1.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a2dr,"_",input${prefix}a2inp1,".",input${prefix}a2oup1.f) }},\n',
    '    content = function(file) {{ ggsav(file, height = input${prefix}a2oup1.h, width = input${prefix}a2oup1.w, \n',
    '                                     plot = {prefix}a2oup1() + theme(legend.position = "none"))\n',
    '  }})\n',
    '  output${prefix}a2oup3 <- renderPlot({{grid.newpage(); grid.draw(g_legend({prefix}a2oup1()))}})\n',
    '  output${prefix}a2oup3.ui <- renderUI({{plotOutput("{prefix}a2oup3", height = 72*convertHeight(\n',
    '    grobHeight(g_legend({prefix}a2oup1())), unitTo="in", valueOnly=TRUE) + 50)}})\n',
    '  output${prefix}a2oup3.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a2dr,"_",input${prefix}a2inp1,"_leg.",input${prefix}a2oup3.f) }},\n',
    '  content = function(file) {{ \n',
    '    grid.newpage(); grid.draw(g_legend({prefix}a2oup1()))\n',
    '    ggsav(file, height = input${prefix}a2oup3.h, width = input${prefix}a2oup3.w, plot = grid.grab())\n',
    '  }})\n',
    '  \n',
    '  {prefix}a2oup2 <- reactive({{\n',
    '    sc2Ddimr({prefix}conf, {prefix}meta, {prefix}dimr, input${prefix}a2dr, input${prefix}a2inp2,\n',
    '             "{prefix}assay_", {prefix}gene, input${prefix}a2ass2, input${prefix}a2sub1, input${prefix}a2sub2,  \n',
    '             input${prefix}a2sub3, input${prefix}a2sub4,\n',
    '             input${prefix}a2min2, input${prefix}a2max2, input${prefix}a2siz, input${prefix}a2ord2,\n',
    '             cList[[input${prefix}a2col2]], sList[input${prefix}a2fsz], \n',
    '             input${prefix}a2asp, input${prefix}a2txt, input${prefix}a2lab2) \n',
    '  }})\n',
    '  output${prefix}a2oup2 <- renderPlot({{{prefix}a2oup2() + theme(legend.position = "none")}})\n',
    '  output${prefix}a2oup2.ui <- renderUI({{plotOutput("{prefix}a2oup2", height = pList[input${prefix}a2psz])}})\n',
    '  output${prefix}a2oup2.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a2dr,"_",input${prefix}a2inp2,".",input${prefix}a2oup2.f) }},\n',
    '    content = function(file) {{ ggsav(file, height = input${prefix}a2oup2.h, width = input${prefix}a2oup2.w, \n',
    '                                     plot = {prefix}a2oup2() + theme(legend.position = "none"))\n',
    '  }})\n',
    '  \n',
    '  output${prefix}a2oup4 <- renderPlot({{grid.newpage(); grid.draw(g_legend({prefix}a2oup2()))}})\n',
    '  output${prefix}a2oup4.ui <- renderUI({{plotOutput("{prefix}a2oup4", height = 72*convertHeight(\n',
    '    grobHeight(g_legend({prefix}a2oup2())), unitTo="in", valueOnly=TRUE) + 50)}})\n',
    '  output${prefix}a2oup4.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a2dr,"_",input${prefix}a2inp2,"_leg.",input${prefix}a2oup4.f) }},\n',
    '  content = function(file) {{ \n',
    '    grid.newpage(); grid.draw(g_legend({prefix}a2oup2()))\n',
    '    ggsav(file, height = input${prefix}a2oup4.h, width = input${prefix}a2oup4.w, plot = grid.grab())\n',
    '  }})\n',
    '  \n',
    '  {prefix}a2oup5 <- reactive({{\n',
    '    sc2Dcomp({prefix}conf, {prefix}meta, input${prefix}a2inp1, input${prefix}a2inp2,\n',
    '             "{prefix}assay_", {prefix}gene, input${prefix}a2ass1, input${prefix}a2ass2, input${prefix}a2sub1, input${prefix}a2sub2,\n',
    '             input${prefix}a2sub3, input${prefix}a2sub4,\n',
    '             input${prefix}a2min1, input${prefix}a2max1, input${prefix}a2min2, input${prefix}a2max2, \n',
    '             input${prefix}a2siz, cList[[input${prefix}a2col2]], sList[input${prefix}a2fsz]) \n',
    '  }})\n',
    '  output${prefix}a2oup5 <- renderPlot({{{prefix}a2oup5() + theme(legend.position = "none")}})\n',
    '  output${prefix}a2oup5.ui <- renderUI({{plotOutput("{prefix}a2oup5", height = pList[input${prefix}a2psz])}})\n',
    '  output${prefix}a2oup5.dl <- downloadHandler( \n',
    '    filename = function() {{ paste0("{prefix}compare_",input${prefix}a2inp1,"_",input${prefix}a2inp2,".",input${prefix}a2oup5.f) }, \n',
    '    content = function(file) {{ ggsav(file, height = input${prefix}a2oup5.h, width = input${prefix}a2oup5.w, \n',
    '                                     plot = {prefix}a2oup5()) \n',
    '  }}) \n',
    '  output${prefix}a2.dt <- renderDataTable({{\n',
    '    ggData = sc2Dcnum({prefix}conf, {prefix}meta, input${prefix}a2inp1, input${prefix}a2inp2,\n',
    '                      "{prefix}assay_", {prefix}gene, input${prefix}a2ass1, input${prefix}a2ass2, input${prefix}a2sub1, input${prefix}a2sub2,\n',
    '                      input${prefix}a2sub3, input${prefix}a2sub4,\n',
    '                      input${prefix}a2min1, input${prefix}a2max1, input${prefix}a2min2, input${prefix}a2max2, input${prefix}a2cut)\n',
    '    datatable(ggData, rownames = FALSE, extensions = "Buttons",\n',
    '              options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel")))\n',
    '  }})\n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainD1
#' @export wrSVmainD1
#'

wrSVmainD1 <- function(prefix) {
  glue::glue(
    '#########################\n',
    '# d1 tab - DEG          #\n',
    '#########################\n',
    '### Populate cluster label dropdown\n',
    'observe({{\n',
    '  # Get all metadata columns that are grouped (grp == TRUE)\n',
    '  cluster_choices <- {prefix}conf[grp == TRUE]$UI\n',
    '  updateSelectInput(session, "{prefix}d1deglab", \n',
    '                   choices = cluster_choices,\n',
    '                   selected = {prefix}def$DEG)\n',
    '}})\n',
    '\n',
    '### Populate cluster selection dropdown based on selected label\n',
    'observeEvent(input${prefix}d1deglab, {{\n',
    '  req(input${prefix}d1deglab)\n',
    '  # Get the unique values for the selected cluster label\n',
    '  cluster_values <- strsplit({prefix}conf[UI == input${prefix}d1deglab]$fID, "\\\\|")[[1]]\n',
    '  updateSelectInput(session, "{prefix}d1degcluster",\n',
    '                   choices = cluster_values,\n',
    '                   selected = cluster_values[1])\n',
    '}})\n',
    '\n',
    '#########################\n',
    '# d1 tab data table     #\n',
    '#########################\n',
    'output${prefix}d1.dt <- renderDataTable({{\n',
    '  ggData <- scDRmarkerdt({prefix}conf, {prefix}meta, {prefix}def, paste0("./{prefix}deg.h5"),\n',
    '                         input${prefix}d1degcluster, input${prefix}d1pval, input${prefix}d1pvaladj,\n',
    '                         input${prefix}d1log2fc, input${prefix}d1diff, input${prefix}d1pctdiffmin,\n',
    '                         input${prefix}d1pctdiffmax)\n',
    '  dt <- datatable(ggData,\n',
    '    rownames = FALSE,\n',
    '    extensions = "Buttons",\n',
    '    options = list(\n',
    '      pageLength = -1,\n',
    '      scrollX = TRUE,\n',
    '      scrollY = 800,\n',
    '      scroller = TRUE,\n',
    '      dom = "Bfrtip",\n',
    '      buttons = list(\n',
    '        "copy", "csv", "excel",\n',
    '        list(extend = "copy",text = "Copy Genes", exportOptions = list(columns = 1))\n',
    '      ),\n',
    '      columnDefs = list(list(className = "dt-center", targets = "_all"))\n',
    '    )\n',
    '  ) %>%\n',
    '    formatRound(columns = c("avg_log2FC"), digits = 2)\n',
    '  # Conditionally format pct.1, pct.2, and pctdiff if they exist\n',
    '  cols_to_format <- c("pct.1", "pct.2")\n',
    '  if ("pctdiff" %in% colnames(ggData)) {{\n',
    '    cols_to_format <- c(cols_to_format, "pctdiff")\n',
    '  }}\n',
    '  dt <- dt %>% formatRound(columns = cols_to_format, digits = 4)\n',
    '  dt\n',
    '}})\n',
    '#########################\n',
    '# d1 tab plot           #\n',
    '#########################\n',
    '{prefix}d1oup1 <- reactive({{\n',
    '  req(input${prefix}d1degcluster, cancelOutput = TRUE)\n',
    '  req(input${prefix}d1deglab, cancelOutput = TRUE)\n',
    '  scDRmarkerplot(\n',
    '    {prefix}conf,\n',
    '    {prefix}meta,\n',
    '    {prefix}dimr,\n',
    '    {prefix}def,\n',
    '    paste0("./{prefix}deg.h5"),\n',
    '    input${prefix}d1degcluster,\n',
    '    input${prefix}d1ass1,\n',
    '    input${prefix}d1dr,\n',
    '    input${prefix}d1deglab,\n',
    '    input${prefix}d1siz,\n',
    '    pList3[[input${prefix}d1psz]],\n',
    '    sList[[input${prefix}d1fsz]],\n',
    '    input${prefix}d1asp\n',
    '  )\n',
    '}})\n',
    'output${prefix}d1oup1 <- renderPlot({{\n',
    '  {prefix}d1oup1()\n',
    '}})\n',
    'output${prefix}d1oup1.ui <- renderUI({{\n',
    '  plotOutput("{prefix}d1oup1", height = pList2[input${prefix}d1psz])\n',
    '}})\n',
    'output${prefix}d1oup1.dl <- downloadHandler(\n',
    '  filename = function() {{\n',
    '    paste0("{prefix}", input${prefix}d1dr, "_", input${prefix}d1ass1, "_", input${prefix}d1deglab, ".", input${prefix}d1oup1.f)\n',
    '  }},\n',
    '  content = function(file) {{\n',
    '    ggsav(file, height = input${prefix}d1oup1.h, width = input${prefix}d1oup1.w, plot = {prefix}d1oup1())\n',
    '  }}\n',
    ')\n',
    'output${prefix}d1sub1.ui <- renderUI({{\n',
    '  sub <- strsplit({prefix}conf[UI == input${prefix}d1sub1]$fID, "\\\\|")[[1]]\n',
    '  checkboxGroupInput("{prefix}d1sub2", "Select which cells to show",\n',
    '    inline = TRUE,\n',
    '    choices = sub, selected = sub\n',
    '  )\n',
    '}})\n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainA3
#' @export wrSVmainA3
#'
wrSVmainA3 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab A3 \n',
    '  getG{prefix}a3inp1 <- reactive({{ \n',
    '    req(input${prefix}a3ass1) \n',
    '    res <- names({prefix}gene[[input${prefix}a3ass1]]) \n',
    '    resDef1 <- {prefix}def$gene1[[input${prefix}a3ass1]] \n',
    '    resDef2 <- {prefix}def$gene2[[input${prefix}a3ass1]] \n',
    '    return(list(res,resDef1,resDef2))\n',
    '  }})\n',
    '  observeEvent(input${prefix}a3ass1, {{\n',
    '    updateSelectizeInput(session, "{prefix}a3inp1", choices = getG{prefix}a3inp1()[[1]], \n',
    '                         server = TRUE, selected = getG{prefix}a3inp1()[[2]], options = list( \n',
    '                           maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) \n',
    '  }})\n',
    '  observeEvent(input${prefix}a3ass1, {{\n',
    '    updateSelectizeInput(session, "{prefix}a3inp2", choices = getG{prefix}a3inp1()[[1]], \n',
    '                         server = TRUE, selected = getG{prefix}a3inp1()[[3]], options = list( \n',
    '                           maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) \n',
    '  }})\n',
    '  output${prefix}a3sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a3sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}a3sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a3sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a3sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}a3sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a3sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}a3sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}a3sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}a3sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}a3sub3) || input${prefix}a3sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a3sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}a3sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}a3sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}a3sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a3sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a3sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}a3sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}a3sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}a3sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}a3sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  {prefix}a3oup1 <- reactive({{\n',
    '    scDRcoex({prefix}conf, {prefix}meta, {prefix}dimr, input${prefix}a3dr, input${prefix}a3inp1, input${prefix}a3inp2, \n',
    '             paste0("{prefix}assay_", input${prefix}a3ass1, ".h5"), {prefix}gene[[input${prefix}a3ass1]], \n',
    '             input${prefix}a3sub1, input${prefix}a3sub2, input${prefix}a3sub3, input${prefix}a3sub4, input${prefix}a3min1, input${prefix}a3max1, input${prefix}a3min2, input${prefix}a3max2, \n',
    '             input${prefix}a3siz, input${prefix}a3col1, input${prefix}a3ord1, \n',
    '             sList[input${prefix}a3fsz], input${prefix}a3asp, input${prefix}a3txt) \n',
    '  }}) \n',
    '  output${prefix}a3oup1 <- renderPlot({{{prefix}a3oup1()}}) \n',
    '  output${prefix}a3oup1.ui <- renderUI({{plotOutput("{prefix}a3oup1", height = pList2[input${prefix}a3psz])}}) \n',
    '  output${prefix}a3oup1.dl <- downloadHandler( \n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a3dr,"_",input${prefix}a3inp1,"_",input${prefix}a3inp2,".",input${prefix}a3oup1.f) }}, \n',
    '    content = function(file) {{ ggsav(file, height = input${prefix}a3oup1.h, width = input${prefix}a3oup1.w, plot = {prefix}a3oup1())\n',
    '  }}) \n',
    '  \n',
    '  output${prefix}a3oup2 <- renderPlot({{scDRcoexLeg(input${prefix}a3inp1, input${prefix}a3inp2, input${prefix}a3col1, sList[input${prefix}a3fsz])}}) \n',
    '  output${prefix}a3oup2.ui <- renderUI({{plotOutput("{prefix}a3oup2", height = "300px")}})\n',
    '  output${prefix}a3oup2.dl <- downloadHandler( \n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}a3dr,"_",input${prefix}a3inp1,"_",input${prefix}a3inp2,"_leg.",input${prefix}a3oup2.f) }}, \n',
    '    content = function(file) {{ ggsav(file, height = 3, width = 4, \n',
    '                                     plot = scDRcoexLeg(input${prefix}a3inp1, input${prefix}a3inp2, input${prefix}a3col1, sList[input${prefix}a3fsz]))\n',
    '  }}) \n',
    '  output${prefix}a3.dt <- renderDataTable({{ \n',
    '    ggData = scDRcoexNum({prefix}conf, {prefix}meta, input${prefix}a3inp1, input${prefix}a3inp2, \n',
    '                         paste0("{prefix}assay_", input${prefix}a3ass1, ".h5"), {prefix}gene[[input${prefix}a3ass1]], \n',
    '                         input${prefix}a3sub1, input${prefix}a3sub2, input${prefix}a3sub3, input${prefix}a3sub4) \n',
    '    datatable(ggData, rownames = FALSE, extensions = "Buttons", \n',
    '              options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>% \n',
    '      formatRound(columns = c("percent"), digits = 2) \n',
    '  }}) \n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainB1
#' @export wrSVmainB1
#'
wrSVmainB1 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab B1 \n',
    '  getG{prefix}b1inp1 <- reactive({{ \n',
    '    req(gsub("^Assay: ", "", input${prefix}b1ass1)) \n',
    '    if(gsub("^Assay: ", "", input${prefix}b1ass1) == "Cell Information"){{ \n',
    '      res <- {prefix}conf[is.na(fID)]$UI \n',
    '      resDef <- {prefix}conf[is.na(fID)]$UI[1] \n',
    '      resLen <- length(res) \n',
    '    }} else {{ \n',
    '      res <- names({prefix}gene[[gsub("^Assay: ", "", input${prefix}b1ass1)]]) \n',
    '      resDef <- {prefix}def$gene1[[gsub("^Assay: ", "", input${prefix}b1ass1)]] \n',
    '      resLen <- 7 \n',
    '    }} \n',
    '    return(list(res,resDef,resLen))\n',
    '  }})\n',
    '  observeEvent(gsub("^Assay: ", "", input${prefix}b1ass1), {{\n',
    '    updateSelectizeInput(session, "{prefix}b1inp2", choices = getG{prefix}b1inp1()[[1]], \n',
    '                         server = TRUE, selected = getG{prefix}b1inp1()[[2]], options = list( \n',
    '                           maxOptions = getG{prefix}b1inp1()[[3]], create = TRUE, \n',
    '                           persist = TRUE, render = I(optCrt))) \n',
    '  }})\n',
    '  output${prefix}b1sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b1sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}b1sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b1sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b1sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}b1sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b1sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b1sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}b1sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}b1sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}b1sub3) || input${prefix}b1sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b1sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}b1sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}b1sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}b1sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b1sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b1sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}b1sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b1sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b1sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}b1sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '\n',
    '  {prefix}b1oup <- reactive({{\n',
    '    scVioBox({prefix}conf, {prefix}meta, input${prefix}b1inp1, input${prefix}b1inp2, \n',
    '             "{prefix}assay_", {prefix}gene, input${prefix}b1ass1, \n',
    '             input${prefix}b1sub1, input${prefix}b1sub2, input${prefix}b1sub3, input${prefix}b1sub4, input${prefix}b1typ, input${prefix}b1pts, \n',
    '             input${prefix}b1stg, input${prefix}b1stp1, input${prefix}b1stp2, \n',
    '             input${prefix}b1siz, sList[input${prefix}b1fsz], input${prefix}b1noi) \n',
    '  }}) \n',
    '  output${prefix}b1oup <- renderPlot({{{prefix}b1oup()}}) \n',
    '  output${prefix}b1oup.ui <- renderUI({{plotOutput("{prefix}b1oup", height = pList2[input${prefix}b1psz])}}) \n',
    '  output${prefix}b1oup.dl <- downloadHandler( \n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}b1typ,"_",input${prefix}b1inp1,"_",input${prefix}b1inp2,".",input${prefix}b1oup.f) }}, \n',
    '    content = function(file) {{ ggsave(file, height = input${prefix}b1oup.h, width = input${prefix}b1oup.w, plot = {prefix}b1oup())\n',
    '  }}) \n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainB2
#' @export wrSVmainB2
#'
wrSVmainB2 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab B2 \n',
    '  observeEvent(input${prefix}b2inp1, {{\n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b2inp2]$fID, "\\\\|")[[1]] \n',
    '    updateSelectizeInput(session, "{prefix}b2ord1", choices = c("Original order", sub), \n',
    '                         server = TRUE, selected = "Original order", options = list( \n',
    '                         create = TRUE, persist = TRUE, render = I(optCrt))) \n',
    '  }}) \n',
    '  output${prefix}b2sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b2sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}b2sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b2sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b2sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}b2sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b2sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b2sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}b2sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}b2sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}b2sub3) || input${prefix}b2sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b2sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}b2sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}b2sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}b2sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b2sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b2sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}b2sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b2sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b2sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}b2sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  \n',
    '  {prefix}b2oup  <- reactive({{\n',
    '    scProp({prefix}conf, {prefix}meta, input${prefix}b2inp1, input${prefix}b2inp2,  \n',
    '           input${prefix}b2sub1, input${prefix}b2sub2, input${prefix}b2sub3, input${prefix}b2sub4, input${prefix}b2ord1, input${prefix}b2ord2, \n',
    '           input${prefix}b2typ, input${prefix}b2flp, sList[input${prefix}b2fsz]) \n',
    '  }})\n',
    '  output${prefix}b2oup <- renderPlot({{{prefix}b2oup()}}) \n',
    '  output${prefix}b2oup.ui <- renderUI({{plotOutput("{prefix}b2oup", height = pList2[input${prefix}b2psz])}}) \n',
    '  output${prefix}b2oup.dl <- downloadHandler( \n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}b2typ,"_",input${prefix}b2inp1,"_",input${prefix}b2inp2,".",input${prefix}b2oup.f) }}, \n',
    '    content = function(file) {{ ggsave(file, height = input${prefix}b2oup.h, width = input${prefix}b2oup.w, plot = {prefix}b2oup())\n',
    '  }}) \n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainB3
#' @export wrSVmainB3
#'
wrSVmainB3 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab B3 \n',
    '  getG{prefix}b3inp1 <- reactive({{ \n',
    '    req(input${prefix}b3ass1) \n',
    '    resDef <- paste0({prefix}def$genes[[input${prefix}b3ass1]], \n',
    '                     collapse = ", ") \n',
    '    return(resDef) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b3ass1, {{ \n',
    '    updateTextAreaInput(session, "{prefix}b3inp", value = getG{prefix}b3inp1()) \n',
    '  }}) \n',
    '  output${prefix}b3sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b3sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}b3sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b3sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b3sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}b3sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b3sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}b3sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}b3sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}b3sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}b3sub3) || input${prefix}b3sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b3sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}b3sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}b3sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}b3sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b3sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b3sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}b3sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}b3sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}b3sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}b3sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}b3oupTxt <- renderUI({{ \n',
    '    geneList = scGeneList(input${prefix}b3inp, {prefix}gene[[input${prefix}b3ass1]]) \n',
    '    if(nrow(geneList) > 50){{ \n',
    '      HTML("More than 50 input genes! Please reduce the gene list!") \n',
    '    }} else {{ \n',
    '      oup = paste0(nrow(geneList[present == TRUE]), " genes OK and will be plotted") \n',
    '      if(nrow(geneList[present == FALSE]) > 0){{ \n',
    '        oup = paste0(oup, "<br/>", \n',
    '                     nrow(geneList[present == FALSE]), " genes not found (", \n',
    '                     paste0(geneList[present == FALSE]$gene, collapse = ", "), ")") \n',
    '      }} \n',
    '      HTML(oup) \n',
    '    }} \n',
    '  }}) \n',
    '  \n',
    '  {prefix}b3oup <- reactive({{\n',
    '    scBubbHeat({prefix}conf, {prefix}meta, input${prefix}b3inp, input${prefix}b3grp, input${prefix}b3plt, \n',
    '               paste0("{prefix}assay_", input${prefix}b3ass1, ".h5"), {prefix}gene[[input${prefix}b3ass1]], \n',
    '               input${prefix}b3sub1, input${prefix}b3sub2, input${prefix}b3sub3, input${prefix}b3sub4, input${prefix}b3scl, \n',
    '               input${prefix}b3row, input${prefix}b3col, cList[[input${prefix}b3cols]], sList[input${prefix}b3fsz], \n',
    '               input${prefix}b3exp, input${prefix}b3max) \n',
    '  }}) \n',
    '  output${prefix}b3oup <- renderPlot({{{prefix}b3oup()}}) \n',
    '  output${prefix}b3oup.ui <- renderUI({{plotOutput("{prefix}b3oup", height = pList3[input${prefix}b3psz])}})\n',
    '  output${prefix}b3oup.dl <- downloadHandler( \n',
    '    filename = function() {{ paste0("{prefix}",input${prefix}b3plt,"_",input${prefix}b3grp,".",input${prefix}b3oup.f) }}, \n',
    '    content = function(file) {{ ggsave(file, height = input${prefix}b3oup.h, width = input${prefix}b3oup.w, plot = {prefix}b3oup())\n',
    '  }}) \n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#' 
#' @rdname wrSVmainS1
#' @export wrSVmainS1
#'
wrSVmainS1 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab S1 \n',
    '  # Reactive image data based on slide selection\n',
    '  {prefix}s1image_data <- reactive({{\n',
    '    # Check if multi-slide data structure exists\n',
    '    if(!is.null({prefix}image$slide_names) && length({prefix}image$slide_names) > 0) {{\n',
    '      # Multi-slide structure exists\n',
    '      if(!is.null(input${prefix}s1slide) && input${prefix}s1slide != "") {{\n',
    '        # User has selected a slide\n',
    '        slide_name <- input${prefix}s1slide\n',
    '      }} else {{\n',
    '        # No slide selected yet, use first slide\n',
    '        slide_name <- {prefix}image$slide_names[1]\n',
    '      }}\n',
    '      result <- list(\n',
    '        coord = {prefix}image$coords[[slide_name]],\n',
    '        bg_image = {prefix}image$bg_images[[slide_name]],\n',
    '        bg_image_hires = {prefix}image$bg_images_hires[[slide_name]],\n',
    '        lowres = {prefix}image$lowres_factors[[slide_name]],\n',
    '        hires_factor = {prefix}image$hires_factors[[slide_name]],\n',
    '        image_type = {prefix}image$image_types[[slide_name]]\n',
    '      )\n',
    '    }} else {{\n',
    '      # Legacy single-slide structure\n',
    '      result <- list(\n',
    '        coord = {prefix}image$coord,\n',
    '        bg_image = {prefix}image$bg_image,\n',
    '        bg_image_hires = if(!is.null({prefix}image$bg_image_hires)) {prefix}image$bg_image_hires else {prefix}image$bg_image,\n',
    '        lowres = {prefix}image$lowres,\n',
    '        hires_factor = if(!is.null({prefix}image$hires_factor)) {prefix}image$hires_factor else 1.0,\n',
    '        image_type = {prefix}image$image_type\n',
    '      )\n',
    '    }}\n',
    '    # Validate that we have all required components\n',
    '    req(result$coord, result$bg_image, result$lowres)\n',
    '    return(result)\n',
    '  }})\n',
    '  \n',
    '  output${prefix}s1sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}s1sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}s1sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s1sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}s1sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}s1sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s1sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}s1sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}s1sub2", label = "Select which cells to show", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  output${prefix}s1sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}s1sub3) || input${prefix}s1sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s1sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}s1sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}s1sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}s1sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s1sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s1sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}s1sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s1sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s1sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}s1sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  \n',
    '  # Spatial transformation state (rotation, flip, and offset) with per-slide memory\n',
    '  {prefix}s1transform <- reactiveValues(rotation = 0, flipH = FALSE, flipV = FALSE, offsetX = 0, offsetY = 0)\n',
    '  # Per-slide transformation memory (survives slide switches)\n',
    '  {prefix}s1slideTransforms <- reactiveValues()\n',
    '  \n',
    '  # Initialize current slide tracking\n',
    '  observe({{\n',
    '    req(input${prefix}s1slide)\n',
    '    if(is.null({prefix}s1slideTransforms$current_slide)) {{\n',
    '      {prefix}s1slideTransforms$current_slide <- input${prefix}s1slide\n',
    '    }}\n',
    '  }}, priority = 100)\n',
    '  \n',
    '  # Save current transform when switching slides\n',
    '  observeEvent(input${prefix}s1slide, {{\n',
    '    req({prefix}s1slideTransforms$current_slide)\n',
    '    \n',
    '    # Save old slide\'s state before switching\n',
    '    if({prefix}s1slideTransforms$current_slide != input${prefix}s1slide) {{\n',
    '      old_slide <- {prefix}s1slideTransforms$current_slide\n',
    '      {prefix}s1slideTransforms[[old_slide]] <- list(\n',
    '        rotation = {prefix}s1transform$rotation,\n',
    '        flipH = {prefix}s1transform$flipH,\n',
    '        flipV = {prefix}s1transform$flipV,\n',
    '        offsetX = {prefix}s1transform$offsetX,\n',
    '        offsetY = {prefix}s1transform$offsetY\n',
    '      )\n',
    '      \n',
    '      # Load new slide\'s saved state (or defaults)\n',
    '      new_slide <- input${prefix}s1slide\n',
    '      {prefix}s1slideTransforms$current_slide <- new_slide\n',
    '      \n',
    '      if(!is.null({prefix}s1slideTransforms[[new_slide]])) {{\n',
    '        saved <- {prefix}s1slideTransforms[[new_slide]]\n',
    '        {prefix}s1transform$rotation <- saved$rotation\n',
    '        {prefix}s1transform$flipH <- saved$flipH\n',
    '        {prefix}s1transform$flipV <- saved$flipV\n',
    '        {prefix}s1transform$offsetX <- saved$offsetX\n',
    '        {prefix}s1transform$offsetY <- saved$offsetY\n',
    '      }} else {{\n',
    '        {prefix}s1transform$rotation <- 0\n',
    '        {prefix}s1transform$flipH <- FALSE\n',
    '        {prefix}s1transform$flipV <- FALSE\n',
    '        {prefix}s1transform$offsetX <- 0\n',
    '        {prefix}s1transform$offsetY <- 0\n',
    '      }}\n',
    '    }}\n',
    '  }}, priority = 50)\n',
    '  \n',
    '  # Auto-save transformations to current slide whenever they change\n',
    '  observe({{\n',
    '    req({prefix}s1slideTransforms$current_slide)\n',
    '    current <- {prefix}s1slideTransforms$current_slide\n',
    '    {prefix}s1slideTransforms[[current]] <- list(\n',
    '      rotation = {prefix}s1transform$rotation,\n',
    '      flipH = {prefix}s1transform$flipH,\n',
    '      flipV = {prefix}s1transform$flipV,\n',
    '      offsetX = {prefix}s1transform$offsetX,\n',
    '      offsetY = {prefix}s1transform$offsetY\n',
    '    )\n',
    '  }})\n',
    '  \n',
    '  # Display current offset\n',
    '  output${prefix}s1offsetDisplay <- renderText({{\n',
    '    paste0("X: ", {prefix}s1transform$offsetX, ", Y: ", {prefix}s1transform$offsetY)\n',
    '  }})\n',
    '  \n',
    '  # Reset transformation\n',
    '  observeEvent(input${prefix}s1reset, {{\n',
    '    {prefix}s1transform$rotation <- 0\n',
    '    {prefix}s1transform$flipH <- FALSE\n',
    '    {prefix}s1transform$flipV <- FALSE\n',
    '    {prefix}s1transform$offsetX <- 0\n',
    '    {prefix}s1transform$offsetY <- 0\n',
    '    {prefix}s1oup1xy$x <- NULL\n',
    '    {prefix}s1oup1xy$y <- NULL\n',
    '  }})\n',
    '  \n',
    '  # Rotate clockwise (add 90 degrees)\n',
    '  observeEvent(input${prefix}s1rotCW, {{\n',
    '    {prefix}s1transform$rotation <- ({prefix}s1transform$rotation + 90) %% 360\n',
    '  }})\n',
    '  \n',
    '  # Rotate counter-clockwise (subtract 90 degrees)\n',
    '  observeEvent(input${prefix}s1rotCCW, {{\n',
    '    {prefix}s1transform$rotation <- ({prefix}s1transform$rotation - 90) %% 360\n',
    '  }})\n',
    '  \n',
    '  # Flip horizontal\n',
    '  observeEvent(input${prefix}s1flipH, {{\n',
    '    {prefix}s1transform$flipH <- !{prefix}s1transform$flipH\n',
    '  }})\n',
    '  \n',
    '  # Flip vertical\n',
    '  observeEvent(input${prefix}s1flipV, {{\n',
    '    {prefix}s1transform$flipV <- !{prefix}s1transform$flipV\n',
    '  }})\n',
    '  \n',
    '  # Offset controls (d-pad) - zoom preserved\n',
    '  observeEvent(input${prefix}s1offsetUp, {{\n',
    '    {prefix}s1transform$offsetY <- {prefix}s1transform$offsetY - 1\n',
    '  }})\n',
    '  \n',
    '  observeEvent(input${prefix}s1offsetDown, {{\n',
    '    {prefix}s1transform$offsetY <- {prefix}s1transform$offsetY + 1\n',
    '  }})\n',
    '  \n',
    '  observeEvent(input${prefix}s1offsetLeft, {{\n',
    '    {prefix}s1transform$offsetX <- {prefix}s1transform$offsetX - 1\n',
    '  }})\n',
    '  \n',
    '  observeEvent(input${prefix}s1offsetRight, {{\n',
    '    {prefix}s1transform$offsetX <- {prefix}s1transform$offsetX + 1\n',
    '  }})\n',
    '  \n',
    '  {prefix}s1oup1xy <- reactiveValues(x = NULL, y = NULL)\n',
    '  \n',
    '  observe({{\n',
    '    brush <- input${prefix}s1inp1.br\n',
    '    if (!is.null(brush)) {{\n',
    '      # Update zoom coordinates when user makes a brush selection\n',
    '      {prefix}s1oup1xy$x <- c(brush$xmin, brush$xmax)\n',
    '      {prefix}s1oup1xy$y <- c(brush$ymin, brush$ymax)\n',
    '    }}\n',
    '    # Note: We do NOT clear zoom when brush becomes NULL\n',
    '    # This prevents zoom from resetting when transformations cause plot to regenerate\n',
    '    # Zoom is only cleared by explicit reset button or double-click\n',
    '  }})  \n',
    '  \n',
    '  # Clear zoom on double-click outside brush area\n',
    '  observeEvent(input${prefix}s1inp1.br_dblclick, {{\n',
    '    {prefix}s1oup1xy$x <- NULL\n',
    '    {prefix}s1oup1xy$y <- NULL\n',
    '  }})\n',
    '  \n',
    '  {prefix}s1oup1br <- reactive({{\n',
    '    req(input${prefix}s1inp1)\n',
    '    # Pass zoom limits to sc2Dspat (NULL when not zoomed)\n',
    '    zoom_lim <- if(!is.null({prefix}s1oup1xy$x)) {{\n',
    '      list(x = {prefix}s1oup1xy$x, y = {prefix}s1oup1xy$y)\n',
    '    }} else {{ NULL }}\n',
    '    sc2Dspat({prefix}conf, {prefix}meta, {prefix}s1image_data(), input${prefix}s1alp, \n',
    '             input${prefix}s1inp1, "{prefix}assay_", {prefix}gene, "Cell Information", \n',
    '             input${prefix}s1sub1, input${prefix}s1sub2, input${prefix}s1sub3, input${prefix}s1sub4, input${prefix}s1min1, input${prefix}s1max1, input${prefix}s1siz*0.6, \n',
    '             cList[[input${prefix}s1col1]], sList[input${prefix}s1fsz]*0.6, FALSE,\n',
    '             rotation = {prefix}s1transform$rotation, flipH = {prefix}s1transform$flipH, flipV = {prefix}s1transform$flipV,\n',
    '             offsetX = {prefix}s1transform$offsetX, offsetY = {prefix}s1transform$offsetY,\n',
    '             zoom_limits = zoom_lim) \n',
    '  }})\n',
    '  output${prefix}s1oup1.br <- renderPlot({{{prefix}s1oup1br() + theme(legend.position = "none")}}) \n',  
    '  \n',
    '  {prefix}s1oup1 <- reactive({{\n',
    '    req(input${prefix}s1inp1)\n',
    '    # Pass zoom limits to sc2Dspat (NULL when not zoomed)\n',
    '    zoom_lim <- if(!is.null({prefix}s1oup1xy$x)) {{\n',
    '      list(x = {prefix}s1oup1xy$x, y = {prefix}s1oup1xy$y)\n',
    '    }} else {{ NULL }}\n',
    '    sc2Dspat({prefix}conf, {prefix}meta, {prefix}s1image_data(), input${prefix}s1alp, \n',
    '             input${prefix}s1inp1, "{prefix}assay_", {prefix}gene, "Cell Information", \n',
    '             input${prefix}s1sub1, input${prefix}s1sub2, input${prefix}s1sub3, input${prefix}s1sub4, input${prefix}s1min1, input${prefix}s1max1, input${prefix}s1siz, \n',
    '             cList[[input${prefix}s1col1]], sList[input${prefix}s1fsz], input${prefix}s1lab1,\n',
    '             rotation = {prefix}s1transform$rotation, flipH = {prefix}s1transform$flipH, flipV = {prefix}s1transform$flipV,\n',
    '             offsetX = {prefix}s1transform$offsetX, offsetY = {prefix}s1transform$offsetY,\n',
    '             zoom_limits = zoom_lim) \n',
    '  }})\n',
    '  output${prefix}s1oup1 <- renderPlot({{\n',
    '    if(is.null({prefix}s1oup1xy$x[1])){{\n',
    '      {prefix}s1oup1() + theme(legend.position = "none")\n',
    '    }} else {{\n',
    '      img_data <- {prefix}s1image_data()\n',
    '      img_w <- dim(img_data$bg_image)[2]  # Image width in pixels\n',
    '      img_h <- dim(img_data$bg_image)[1]  # Image height in pixels\n',
    '      # Calculate zoom factor based on how much of the image is selected\n',
    '      zoom_factor_x <- img_w / diff({prefix}s1oup1xy$x)\n',
    '      zoom_factor_y <- img_h / diff({prefix}s1oup1xy$y)\n',
    '      zoom_factor <- min(zoom_factor_x, zoom_factor_y)\n',
    '      adjSiz <- input${prefix}s1siz * zoom_factor\n',
    '      {prefix}s1oup1() + theme(legend.position = "none") + \n',
    '        coord_fixed(ratio = 1, \n',
    '                   xlim = {prefix}s1oup1xy$x, \n',
    '                   ylim = rev({prefix}s1oup1xy$y),  # Reverse for scale_y_reverse\n',
    '                   expand = FALSE) + \n',
    '        scale_size_continuous(range = c(0, adjSiz), limits = c(0,1))\n',
    '    }}\n',
    '  }})\n',
    '  output${prefix}s1oup1.ui <- renderUI({{plotOutput("{prefix}s1oup1", height = pList[input${prefix}s1psz])}})\n',
    '  output${prefix}s1oup1.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}spatial_",input${prefix}s1inp1,".",input${prefix}s1oup1.f) }},\n',
    '    content = function(file) {{ \n',
    '      if(is.null({prefix}s1oup1xy$x[1])){{\n',
    '        ggsav(file, height = input${prefix}s1oup1.h, width = input${prefix}s1oup1.w, \n',
    '              plot = {prefix}s1oup1() + theme(legend.position = "none"))\n',
    '      }} else {{\n',
    '        img_data <- {prefix}s1image_data()\n',
    '        img_w <- dim(img_data$bg_image)[2]\n',
    '        img_h <- dim(img_data$bg_image)[1]\n',
    '        zoom_factor_x <- img_w / diff({prefix}s1oup1xy$x)\n',
    '        zoom_factor_y <- img_h / diff({prefix}s1oup1xy$y)\n',
    '        zoom_factor <- min(zoom_factor_x, zoom_factor_y)\n',
    '        adjSiz <- input${prefix}s1siz * zoom_factor\n',
    '        ggsav(file, height = input${prefix}s1oup1.h, width = input${prefix}s1oup1.w, \n',
    '              plot = {prefix}s1oup1() + theme(legend.position = "none") + \n',
    '                coord_fixed(ratio = 1, \n',
    '                           xlim = {prefix}s1oup1xy$x, \n',
    '                           ylim = rev({prefix}s1oup1xy$y), \n',
    '                           expand = FALSE) + \n',
    '                scale_size_continuous(range = c(0, adjSiz), limits = c(0,1)))\n',
    '      }}\n',
    '  }})\n',
    '  output${prefix}s1oup3 <- renderPlot({{grid.newpage(); grid.draw(g_legend({prefix}s1oup1()))}})\n',
    '  output${prefix}s1oup3.ui <- renderUI({{plotOutput("{prefix}s1oup3", height = 72*convertHeight(\n',
    '    grobHeight(g_legend({prefix}s1oup1())), unitTo="in", valueOnly=TRUE) + 50)}})\n',
    '  output${prefix}s1oup3.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}spatial_",input${prefix}s1inp1,"_leg.",input${prefix}s1oup3.f) }},\n',
    '    content = function(file) {{ \n',
    '      grid.newpage(); grid.draw(g_legend({prefix}s1oup1()))\n',
    '      ggsav(file, height = input${prefix}s1oup3.h, width = input${prefix}s1oup3.w, plot = grid.grab())\n',
    '    }}) \n',
    '  \n',
    '  output${prefix}s1.dt <- renderDataTable({{\n',
    '    req(input${prefix}s1inp1, input${prefix}s1splt)\n',
    '    img_data <- {prefix}s1image_data()\n',
    '    # Use imagerow and imagecol in correct order (matching Seurat)\n',
    '    ggData = data.table(img_data$coord[, c("imagerow", "imagecol")])\n',
    '    colnames(ggData) = c("UMAP_2","UMAP_1")\n',
    '    # Scale coordinates by lowres factor\n',
    '    ggData$UMAP_2 = ggData$UMAP_2 * img_data$lowres\n',
    '    ggData$UMAP_1 = ggData$UMAP_1 * img_data$lowres\n',
    '    tmpdimr = list(); tmpdimr$umap = ggData\n',
    '    \n',
    '    # Handle metadata subsetting - check if cellID matching is needed\n',
    '    spatial_cells <- rownames(img_data$coord)\n',
    '    if("cellID" %in% colnames({prefix}meta) && any(spatial_cells %in% {prefix}meta$cellID)) {{\n',
    '      # Case 1: cellID exists and matches - use proper subsetting\n',
    '      meta_subset <- {prefix}meta[cellID %in% spatial_cells]\n',
    '      setkey(meta_subset, cellID)\n',
    '      # Ensure tmpdimr rows match meta_subset\n',
    '      tmpdimr$umap$cellID <- spatial_cells\n',
    '      setkey(tmpdimr$umap, cellID)\n',
    '      tmpdimr$umap <- meta_subset[tmpdimr$umap, on = "cellID"][, .(UMAP_1, UMAP_2)]\n',
    '    }} else {{\n',
    '      # Case 2: cellID doesn\'t match spatial_cells or doesn\'t exist\n',
    '      # Use direct indexing - assumes spatial and metadata are aligned\n',
    '      meta_subset <- {prefix}meta[1:nrow(img_data$coord)]\n',
    '    }}\n',
    '    \n',
    '    ggData = sc2Dnum({prefix}conf, meta_subset, tmpdimr, "umap", {prefix}s1oup1xy$x, {prefix}s1oup1xy$y, input${prefix}s1inp1,\n',
    '                     "{prefix}assay_", {prefix}gene, "Cell Information", input${prefix}s1sub1, input${prefix}s1sub2, input${prefix}s1splt)\n',
    '    datatable(ggData, rownames = FALSE, extensions = "Buttons",\n',
    '              options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>%\n',
    '      formatRound(columns = c("pctZoom"), digits = 2)\n',
    '  }})\n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainS2
#' @export wrSVmainS2
#'
wrSVmainS2 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab S2 \n',
    '  # Reactive image data based on slide selection\n',
    '  {prefix}s2image_data <- reactive({{\n',
    '    # Check if multi-slide data structure exists\n',
    '    if(!is.null({prefix}image$slide_names) && length({prefix}image$slide_names) > 0) {{\n',
    '      # Multi-slide structure exists\n',
    '      if(!is.null(input${prefix}s2slide) && input${prefix}s2slide != "") {{\n',
    '        # User has selected a slide\n',
    '        slide_name <- input${prefix}s2slide\n',
    '      }} else {{\n',
    '        # No slide selected yet, use first slide\n',
    '        slide_name <- {prefix}image$slide_names[1]\n',
    '      }}\n',
    '      result <- list(\n',
    '        coord = {prefix}image$coords[[slide_name]],\n',
    '        bg_image = {prefix}image$bg_images[[slide_name]],\n',
    '        bg_image_hires = {prefix}image$bg_images_hires[[slide_name]],\n',
    '        lowres = {prefix}image$lowres_factors[[slide_name]],\n',
    '        hires_factor = {prefix}image$hires_factors[[slide_name]],\n',
    '        image_type = {prefix}image$image_types[[slide_name]]\n',
    '      )\n',
    '    }} else {{\n',
    '      # Legacy single-slide structure\n',
    '      result <- list(\n',
    '        coord = {prefix}image$coord,\n',
    '        bg_image = {prefix}image$bg_image,\n',
    '        bg_image_hires = if(!is.null({prefix}image$bg_image_hires)) {prefix}image$bg_image_hires else {prefix}image$bg_image,\n',
    '        lowres = {prefix}image$lowres,\n',
    '        hires_factor = if(!is.null({prefix}image$hires_factor)) {prefix}image$hires_factor else 1.0,\n',
    '        image_type = {prefix}image$image_type\n',
    '      )\n',
    '    }}\n',
    '    # Validate that we have all required components\n',
    '    req(result$coord, result$bg_image, result$lowres)\n',
    '    return(result)\n',
    '  }})\n',
    '  \n',
    '    output${prefix}s2sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}s2sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}s2sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s2sub1non, {{\n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}s2sub1]$fID, "\\\\|")[[1]]\n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}s2sub2", label = "Select which cells to show",\n',
    '                             choices = sub, selected = NULL, inline = TRUE)\n',
    '  }})\n',
    '  observeEvent(input${prefix}s2sub1all, {{\n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}s2sub1]$fID, "\\\\|")[[1]]\n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}s2sub2", label = "Select which cells to show",\n',
    '                             choices = sub, selected = sub, inline = TRUE)\n',
    '  }})\n',
    '  output${prefix}s2sub3.ui <- renderUI({{ \n',
    '    if(is.null(input${prefix}s2sub3) || input${prefix}s2sub3 == "(none)") return(NULL) \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s2sub3]$fID, "\\\\|")[[1]] \n',
    '    tagList( \n',
    '      checkboxGroupInput("{prefix}s2sub4", "2nd filter - keep:", \n',
    '                         inline = TRUE, choices = sub, selected = sub), \n',
    '      actionButton("{prefix}s2sub3all", "All", class = "btn btn-primary"), \n',
    '      actionButton("{prefix}s2sub3non", "None", class = "btn btn-primary") \n',
    '    ) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s2sub3non, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s2sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}s2sub4", choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}s2sub3all, {{ \n',
    '    sub <- strsplit({prefix}conf[UI == input${prefix}s2sub3]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, "{prefix}s2sub4", choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '  \n',
    '  # Spatial transformation state (rotation, flip, and offset) with per-slide memory\n',
    '  {prefix}s2transform <- reactiveValues(rotation = 0, flipH = FALSE, flipV = FALSE, offsetX = 0, offsetY = 0)\n',
    '  # Per-slide transformation memory (survives slide switches)\n',
    '  {prefix}s2slideTransforms <- reactiveValues()\n',
    '  \n',
    '  # Initialize current slide tracking\n',
    '  observe({{\n',
    '    req(input${prefix}s2slide)\n',
    '    if(is.null({prefix}s2slideTransforms$current_slide)) {{\n',
    '      {prefix}s2slideTransforms$current_slide <- input${prefix}s2slide\n',
    '    }}\n',
    '  }}, priority = 100)\n',
    '  \n',
    '  # Save current transform when switching slides\n',
    '  observeEvent(input${prefix}s2slide, {{\n',
    '    req({prefix}s2slideTransforms$current_slide)\n',
    '    \n',
    '    # Save old slide\'s state before switching\n',
    '    if({prefix}s2slideTransforms$current_slide != input${prefix}s2slide) {{\n',
    '      old_slide <- {prefix}s2slideTransforms$current_slide\n',
    '      {prefix}s2slideTransforms[[old_slide]] <- list(\n',
    '        rotation = {prefix}s2transform$rotation,\n',
    '        flipH = {prefix}s2transform$flipH,\n',
    '        flipV = {prefix}s2transform$flipV,\n',
    '        offsetX = {prefix}s2transform$offsetX,\n',
    '        offsetY = {prefix}s2transform$offsetY\n',
    '      )\n',
    '      \n',
    '      # Load new slide\'s saved state (or defaults)\n',
    '      new_slide <- input${prefix}s2slide\n',
    '      {prefix}s2slideTransforms$current_slide <- new_slide\n',
    '      \n',
    '      if(!is.null({prefix}s2slideTransforms[[new_slide]])) {{\n',
    '        saved <- {prefix}s2slideTransforms[[new_slide]]\n',
    '        {prefix}s2transform$rotation <- saved$rotation\n',
    '        {prefix}s2transform$flipH <- saved$flipH\n',
    '        {prefix}s2transform$flipV <- saved$flipV\n',
    '        {prefix}s2transform$offsetX <- saved$offsetX\n',
    '        {prefix}s2transform$offsetY <- saved$offsetY\n',
    '      }} else {{\n',
    '        {prefix}s2transform$rotation <- 0\n',
    '        {prefix}s2transform$flipH <- FALSE\n',
    '        {prefix}s2transform$flipV <- FALSE\n',
    '        {prefix}s2transform$offsetX <- 0\n',
    '        {prefix}s2transform$offsetY <- 0\n',
    '      }}\n',
    '    }}\n',
    '  }}, priority = 50)\n',
    '  \n',
    '  # Auto-save transformations to current slide whenever they change\n',
    '  observe({{\n',
    '    req({prefix}s2slideTransforms$current_slide)\n',
    '    current <- {prefix}s2slideTransforms$current_slide\n',
    '    {prefix}s2slideTransforms[[current]] <- list(\n',
    '      rotation = {prefix}s2transform$rotation,\n',
    '      flipH = {prefix}s2transform$flipH,\n',
    '      flipV = {prefix}s2transform$flipV,\n',
    '      offsetX = {prefix}s2transform$offsetX,\n',
    '      offsetY = {prefix}s2transform$offsetY\n',
    '    )\n',
    '  }})\n',
    '  \n',
    '  # Display current offset\n',
    '  output${prefix}s2offsetDisplay <- renderText({{\n',
    '    paste0("X: ", {prefix}s2transform$offsetX, ", Y: ", {prefix}s2transform$offsetY)\n',
    '  }})\n',
    '  \n',
    '  # Reset transformation\n',
    '  observeEvent(input${prefix}s2reset, {{\n',
    '    {prefix}s2transform$rotation <- 0\n',
    '    {prefix}s2transform$flipH <- FALSE\n',
    '    {prefix}s2transform$flipV <- FALSE\n',
    '    {prefix}s2transform$offsetX <- 0\n',
    '    {prefix}s2transform$offsetY <- 0\n',
    '  }})\n',
    '  \n',
    '  # Rotate clockwise (add 90 degrees)\n',
    '  observeEvent(input${prefix}s2rotCW, {{\n',
    '    {prefix}s2transform$rotation <- ({prefix}s2transform$rotation + 90) %% 360\n',
    '  }})\n',
    '  \n',
    '  # Rotate counter-clockwise (subtract 90 degrees)\n',
    '  observeEvent(input${prefix}s2rotCCW, {{\n',
    '    {prefix}s2transform$rotation <- ({prefix}s2transform$rotation - 90) %% 360\n',
    '  }})\n',
    '  \n',
    '  # Flip horizontal\n',
    '  observeEvent(input${prefix}s2flipH, {{\n',
    '    {prefix}s2transform$flipH <- !{prefix}s2transform$flipH\n',
    '  }})\n',
    '  \n',
    '  # Flip vertical\n',
    '  observeEvent(input${prefix}s2flipV, {{\n',
    '    {prefix}s2transform$flipV <- !{prefix}s2transform$flipV\n',
    '  }})\n',
    '  \n',
    '  # Offset controls (d-pad)\n',
    '  observeEvent(input${prefix}s2offsetUp, {{\n',
    '    {prefix}s2transform$offsetY <- {prefix}s2transform$offsetY - 1\n',
    '  }})\n',
    '  \n',
    '  observeEvent(input${prefix}s2offsetDown, {{\n',
    '    {prefix}s2transform$offsetY <- {prefix}s2transform$offsetY + 1\n',
    '  }})\n',
    '  \n',
    '  observeEvent(input${prefix}s2offsetLeft, {{\n',
    '    {prefix}s2transform$offsetX <- {prefix}s2transform$offsetX - 1\n',
    '  }})\n',
    '  \n',
    '  observeEvent(input${prefix}s2offsetRight, {{\n',
    '    {prefix}s2transform$offsetX <- {prefix}s2transform$offsetX + 1\n',
    '  }})\n',
    '  \n',
    '  {prefix}s2oup1 <- reactive({{\n',
    '    req(input${prefix}s2inp1)\n',
    '    sc2Dspat({prefix}conf, {prefix}meta, {prefix}s2image_data(), input${prefix}s2alp, \n',
    '             input${prefix}s2inp1, "{prefix}assay_", {prefix}gene, "Cell Information", \n',
    '             input${prefix}s2sub1, input${prefix}s2sub2, input${prefix}s2sub3, input${prefix}s2sub4, input${prefix}s2min1, input${prefix}s2max1, input${prefix}s2siz, \n',
    '             cList[[input${prefix}s2col1]], sList[input${prefix}s2fsz], input${prefix}s2lab1,\n',
    '             rotation = {prefix}s2transform$rotation, flipH = {prefix}s2transform$flipH, flipV = {prefix}s2transform$flipV,\n',
    '             offsetX = {prefix}s2transform$offsetX, offsetY = {prefix}s2transform$offsetY,\n',
    '             zoom_limits = NULL) \n',
    '  }})\n',
    '  output${prefix}s2oup1 <- renderPlot({{{prefix}s2oup1() + theme(legend.position = "none")}})\n',
    '  output${prefix}s2oup1.ui <- renderUI({{plotOutput("{prefix}s2oup1", height = pList[input${prefix}s2psz])}})\n',
    '  output${prefix}s2oup1.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}spatial_",input${prefix}s2inp1,".",input${prefix}s2oup1.f) }},\n',
    '    content = function(file) {{ ggsav(file, height = input${prefix}s2oup1.h, width = input${prefix}s2oup1.w, \n',
    '                                     plot = {prefix}s2oup1() + theme(legend.position = "none"))\n',
    '  }})\n',
    '  output${prefix}s2oup3 <- renderPlot({{grid.newpage(); grid.draw(g_legend({prefix}s2oup1()))}})\n',
    '  output${prefix}s2oup3.ui <- renderUI({{plotOutput("{prefix}s2oup3", height = 72*convertHeight(\n',
    '    grobHeight(g_legend({prefix}s2oup1())), unitTo="in", valueOnly=TRUE) + 50)}})\n',
    '  output${prefix}s2oup3.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}spatial_",input${prefix}s2inp1,"_leg.",input${prefix}s2oup3.f) }},\n',
    '    content = function(file) {{ \n',
    '      grid.newpage(); grid.draw(g_legend({prefix}s2oup1()))\n',
    '      ggsav(file, height = input${prefix}s2oup3.h, width = input${prefix}s2oup3.w, plot = grid.grab())\n',
    '  }})\n',
    '  {prefix}s2oup2 <- reactive({{\n',
    '    req(input${prefix}s2inp2)\n',
    '    sc2Dspat({prefix}conf, {prefix}meta, {prefix}s2image_data(), input${prefix}s2alp, \n',
    '             input${prefix}s2inp2, "{prefix}assay_", {prefix}gene, "Cell Information", \n',
    '             input${prefix}s2sub1, input${prefix}s2sub2, input${prefix}s2sub3, input${prefix}s2sub4, input${prefix}s2min2, input${prefix}s2max2, input${prefix}s2siz, \n',
    '             cList[[input${prefix}s2col2]], sList[input${prefix}s2fsz], input${prefix}s2lab2,\n',
    '             rotation = {prefix}s2transform$rotation, flipH = {prefix}s2transform$flipH, flipV = {prefix}s2transform$flipV,\n',
    '             offsetX = {prefix}s2transform$offsetX, offsetY = {prefix}s2transform$offsetY,\n',
    '             zoom_limits = NULL) \n',
    '  }})\n',
    '  output${prefix}s2oup2 <- renderPlot({{{prefix}s2oup2() + theme(legend.position = "none")}})\n',
    '  output${prefix}s2oup2.ui <- renderUI({{plotOutput("{prefix}s2oup2", height = pList[input${prefix}s2psz])}})\n',
    '  output${prefix}s2oup2.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}spatial_",input${prefix}s2inp2,".",input${prefix}s2oup4.f) }},\n',
    '    content = function(file) {{ ggsav(file, height = input${prefix}s2oup2.h, width = input${prefix}s2oup2.w, \n',
    '                                     plot = {prefix}s2oup2() + theme(legend.position = "none"))\n',
    '  }})\n',
    '  output${prefix}s2oup4 <- renderPlot({{grid.newpage(); grid.draw(g_legend({prefix}s2oup2()))}})\n',
    '  output${prefix}s2oup4.ui <- renderUI({{plotOutput("{prefix}s2oup4", height = 72*convertHeight(\n',
    '    grobHeight(g_legend({prefix}s2oup2())), unitTo="in", valueOnly=TRUE) + 50)}})\n',
    '  output${prefix}s2oup4.dl <- downloadHandler(\n',
    '    filename = function() {{ paste0("{prefix}spatial_",input${prefix}s2inp2,"_leg.",input${prefix}s2oup4.f) }},\n',
    '    content = function(file) {{ \n',
    '      grid.newpage(); grid.draw(g_legend({prefix}s2oup2()))\n',
    '      ggsav(file, height = input${prefix}s2oup4.h, width = input${prefix}s2oup4.w, plot = grid.grab())\n',
    '  }})\n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVmainT1
#' @export wrSVmainT1
#'
wrSVmainT1 <- function(prefix) {
  glue::glue(
    '  ### Functions for tab T1 \n',
    '  updateSelectizeInput(session, "{prefix}t1gene", choices = {prefix}bw$chrGene$gene, server = TRUE,  \n',
    '                       selected = {prefix}bw$chrGene$gene[42], options = list( \n',
    '                         maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) \n',
    '  observe({{ \n',
    '    files <- c("no file selected", list.files(path = "./bed_files", pattern = "*.bed|*.tsv")) \n',
    '    updateSelectInput(session, "{prefix}t1bed", choices = files, selected = "no file selected") \n',
    '  }}) \n',
    '  output${prefix}t1sub1.ui <- renderUI({{ \n',
    '    sub = dir(paste0("{prefix}bw_", input${prefix}t1grp), full.names = FALSE, pattern = "*.bw") \n',
    '    sub = gsub(".bw$", "", sub) \n',
    '    checkboxGroupInput("{prefix}t1sub2", "Select which tracks to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}t1sub1non, {{  \n',
    '    sub = dir(paste0("{prefix}bw_", input${prefix}t1grp), full.names = FALSE, pattern = "*.bw") \n',
    '    sub = gsub(".bw$", "", sub) \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}t1sub2", label = "Select which tracks to show",  \n',
    '                             choices = sub, selected = NULL, inline = TRUE)  \n',
    '  }})  \n',
    '  observeEvent(input${prefix}t1sub1all, {{  \n',
    '    sub = dir(paste0("{prefix}bw_", input${prefix}t1grp), full.names = FALSE, pattern = "*.bw") \n',
    '    sub = gsub(".bw$", "", sub) \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}t1sub2", label = "Select which tracks to show",  \n',
    '                             choices = sub, selected = sub, inline = TRUE)  \n',
    '  }})  \n',
    '  \n',
    '  {prefix}bwGroup <- reactive({{ \n',
    '    req(input${prefix}t1grp) \n',
    '    bigWigs <- dir(paste0("{prefix}bw_", input${prefix}t1grp), full.names = TRUE) \n',
    '    bw_samples <- read_coldata(bws = bigWigs, build = {prefix}bw$genome) \n',
    '    if(!is.null(input${prefix}t1sub2[[1]])) {{ \n',
    '      tmp <- bw_samples[bw_files %in% paste0( \n',
    '        "{prefix}bw_", input${prefix}t1grp, "/", input${prefix}t1sub2, ".bw"), ] \n',
    '      if(nrow(tmp) > 0){{bw_samples <- tmp}} \n',
    '    }} \n',
    '    return(bw_samples) \n',
    '  }}) \n',
    '  {prefix}t1tr <- eventReactive(input${prefix}t1update, {{ \n',
    '    # Process track color \n',
    '    tmp = strsplit({prefix}conf[UI == input${prefix}t1grp]$fCL, "\\\\|")[[1]] \n',
    '    names(tmp) = strsplit({prefix}conf[UI == input${prefix}t1grp]$fID, "\\\\|")[[1]] \n',
    '    if(!is.null(input${prefix}t1sub2)){{ \n',
    '      track_col = tmp[input${prefix}t1sub2] \n',
    '    }} else {{ \n',
    '      track_col = tmp \n',
    '    }} \n',
    '    if(is.na(track_col[[1]])){{track_col = "grey"}} \n',
    '    if(input${prefix}t1col == FALSE){{track_col = "grey"}} \n',
    '    # Collect inputs \n',
    '    inp <- list(gene = input${prefix}t1gene, \n',
    '                chr  = input${prefix}t1chr, \n',
    '                srt  = input${prefix}t1srt, \n',
    '                end  = input${prefix}t1end, \n',
    '                bed  = input${prefix}t1bed, \n',
    '                extL = input${prefix}t1extL, \n',
    '                extR = input${prefix}t1extR, \n',
    '                col  = track_col, \n',
    '                bw_colData = {prefix}bwGroup()) \n',
    '    if (input${prefix}t1sel == "Region"){{inp$gene = NULL}} \n',
    '    if (input${prefix}t1bed == "no file selected"){{inp$bed = NULL}} \n',
    '    inp \n',
    '  }}, ignoreNULL = FALSE) \n',
    '  output${prefix}t1track <- renderPlot({{ \n',
    '    inp <- {prefix}t1tr() \n',
    '    scTrackplot("./", inp$bw_colData, inp$gene, {prefix}bw, inp$chr, inp$srt, inp$end, \n',
    '                inp$extL, inp$extR, inp$bed, "{prefix}bw.gtf.gz", binSize = 100,  \n',
    '                input${prefix}t1dgt, input${prefix}t1asg, input${prefix}t1gth,  \n',
    '                input${prefix}t1ath, input${prefix}t1sha, input${prefix}t1gsz,  \n',
    '                input${prefix}t1tnp, input${prefix}t1ctx, inp$col) \n',
    '  }}) \n',
    '  output${prefix}t1track.ui <- renderUI({{ \n',
    '    plotOutput("{prefix}t1track",  \n',
    '               height = paste0(input${prefix}t1track.h, "px"),  \n',
    '               width =  paste0(input${prefix}t1track.w, "px")) \n',
    '  }}) \n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R - Module Score tab
#'
#' @rdname wrSVmainMOD
#' @export wrSVmainMOD
#'
wrSVmainMOD <- function(prefix) {
  glue::glue(
    '  ### Functions for Module Score tab \n',
    '  output${prefix}comb_sub1.ui <- renderUI({{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}comb_sub1]$fID, "\\\\|")[[1]] \n',
    '    checkboxGroupInput("{prefix}comb_sub2", "Select which cells to show", inline = TRUE, \n',
    '                       choices = sub, selected = sub) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}comb_sub1non, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}comb_sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}comb_sub2", \n',
    '                             choices = sub, selected = NULL, inline = TRUE) \n',
    '  }}) \n',
    '  observeEvent(input${prefix}comb_sub1all, {{ \n',
    '    sub = strsplit({prefix}conf[UI == input${prefix}comb_sub1]$fID, "\\\\|")[[1]] \n',
    '    updateCheckboxGroupInput(session, inputId = "{prefix}comb_sub2", \n',
    '                             choices = sub, selected = sub, inline = TRUE) \n',
    '  }}) \n',
    '\n',
    '  output${prefix}comb_mod_geneTxt <- renderUI({{ \n',
    '    geneList <- scGeneList(input${prefix}comb_mod_inp, {prefix}gene[[input${prefix}comb_mod_ass]]) \n',
    '    if (nrow(geneList) > 50) {{ \n',
    '      HTML("<span style=\'color:red\'>More than 50 genes! Please reduce the list.</span>") \n',
    '    }} else {{ \n',
    '      ok  <- nrow(geneList[present == TRUE]) \n',
    '      bad <- nrow(geneList[present == FALSE]) \n',
    '      oup <- paste0(ok, " genes found and will be used for scoring") \n',
    '      if (bad > 0) \n',
    '        oup <- paste0(oup, "<br/><span style=\'color:orange\'>", bad, " not found: ", \n',
    '                      paste0(geneList[present == FALSE]$gene, collapse = ", "), "</span>") \n',
    '      HTML(oup) \n',
    '    }} \n',
    '  }}) \n',
    '\n',
    '  {prefix}comb_mod_score <- reactive({{ \n',
    '    geneList <- scGeneList(input${prefix}comb_mod_inp, {prefix}gene[[input${prefix}comb_mod_ass]]) \n',
    '    shiny::validate( \n',
    '      need(nrow(geneList[present == TRUE]) >= 2, \n',
    '           "Please provide at least 2 valid genes."), \n',
    '      need(nrow(geneList) <= 50, \n',
    '           "More than 50 genes - please reduce the list.") \n',
    '    ) \n',
    '    inpH5 <- paste0("{prefix}assay_", input${prefix}comb_mod_ass, ".h5") \n',
    '    scModuleScore({prefix}gene[[input${prefix}comb_mod_ass]], inpH5, geneList, \n',
    '                  seed = 42) \n',
    '  }}) \n',
    '\n',
    '  {prefix}comb_mod_dr_oup <- reactive({{ \n',
    '    score  <- {prefix}comb_mod_score() \n',
    '    inpdr  <- input${prefix}comb_mod_dr \n',
    '    ggData <- data.table({prefix}dimr[[inpdr]]); colnames(ggData) <- c("X","Y") \n',
    '    rat    <- (max(ggData$X) - min(ggData$X)) / (max(ggData$Y) - min(ggData$Y)) \n',
    '    sub1   <- if (is.null(input${prefix}comb_sub1)) {prefix}conf$UI[1] else input${prefix}comb_sub1 \n',
    '    ggData$sub <- {prefix}meta[, {prefix}conf[UI == sub1]$ID, with = FALSE][[1]] \n',
    '    ggData$val <- score \n',
    '    bgCells <- FALSE \n',
    '    if (length(input${prefix}comb_sub2) != 0 && \n',
    '        length(input${prefix}comb_sub2) != nlevels(ggData$sub)) {{ \n',
    '      bgCells <- TRUE \n',
    '      ggData2 <- ggData[!sub %in% input${prefix}comb_sub2] \n',
    '      ggData  <- ggData[sub  %in% input${prefix}comb_sub2] \n',
    '    }} \n',
    '    if (input${prefix}comb_mod_ord == "Max-1st") {{ \n',
    '      ggData <- ggData[order(val)] \n',
    '    }} else if (input${prefix}comb_mod_ord == "Min-1st") {{ \n',
    '      ggData <- ggData[order(-val)] \n',
    '    }} else if (input${prefix}comb_mod_ord == "Random") {{ \n',
    '      ggData <- ggData[sample(nrow(ggData))] \n',
    '    }} \n',
    '    inpfsz <- sList[input${prefix}comb_mod_fsz] \n',
    '    inpcol <- cList[[input${prefix}comb_mod_col]] \n',
    '    ggOut  <- ggplot(ggData, aes(X, Y, color = val)) \n',
    '    if (bgCells) \n',
    '      ggOut <- ggOut + geom_point(data = ggData2, color = "snow2", \n',
    '                                  size = input${prefix}comb_mod_siz / 2, shape = 16) \n',
    '    ggOut <- ggOut + \n',
    '      geom_point(size = input${prefix}comb_mod_siz, shape = 16) + \n',
    '      xlab(paste0(inpdr,"1")) + ylab(paste0(inpdr,"2")) + \n',
    '      sctheme(base_size = inpfsz, XYval = input${prefix}comb_mod_txt) + \n',
    '      scale_color_gradientn("Module Score  ", colours = inpcol) + \n',
    '      guides(color = guide_colorbar(barwidth = 15)) \n',
    '    asp <- input${prefix}comb_mod_asp \n',
    '    if (asp == "Square") ggOut <- ggOut + coord_fixed(ratio = 1) \n',
    '    else if (asp == "Fixed") ggOut <- ggOut + coord_fixed(ratio = rat) \n',
    '    ggOut \n',
    '  }}) \n',
    '  output${prefix}comb_mod_dr_oup.ui <- renderUI({{ \n',
    '    plotOutput("{prefix}comb_mod_dr_oup", height = pList[input${prefix}comb_mod_psz]) \n',
    '  }}) \n',
    '  output${prefix}comb_mod_dr_oup <- renderPlot({{ \n',
    '    {prefix}comb_mod_dr_oup() + theme(legend.position = "none") \n',
    '  }}) \n',
    '  output${prefix}comb_mod_leg_oup.ui <- renderUI({{ \n',
    '    plotOutput("{prefix}comb_mod_leg_oup", \n',
    '               height = 72 * convertHeight( \n',
    '                 grobHeight(g_legend({prefix}comb_mod_dr_oup())), \n',
    '                 unitTo = "in", valueOnly = TRUE) + 50) \n',
    '  }}) \n',
    '  output${prefix}comb_mod_leg_oup <- renderPlot({{ \n',
    '    grid.newpage(); grid.draw(g_legend({prefix}comb_mod_dr_oup())) \n',
    '  }}) \n',
    '  output${prefix}comb_mod_dr_oup.dl <- downloadHandler( \n',
    '    filename = function() {{ \n',
    '      paste0("{prefix}modscore_dimred_", input${prefix}comb_mod_dr, \n',
    '             ".", input${prefix}comb_mod_dr_oup.f) \n',
    '    }}, \n',
    '    content = function(file) {{ \n',
    '      p <- {prefix}comb_mod_dr_oup() + theme(legend.position = "none") \n',
    '      ggsav(file, height = input${prefix}comb_mod_dr_oup.h, \n',
    '             width = input${prefix}comb_mod_dr_oup.w, plot = p) \n',
    '    }} \n',
    '  ) \n',
    '\n',
    '  {prefix}comb_mod_vln_oup <- reactive({{ \n',
    '    score <- {prefix}comb_mod_score() \n',
    '    sub1  <- if (is.null(input${prefix}comb_sub1)) {prefix}conf$UI[1] else input${prefix}comb_sub1 \n',
    '    ggData <- data.table( \n',
    '      X   = {prefix}meta[, {prefix}conf[UI == input${prefix}comb_grp]$ID, with = FALSE][[1]], \n',
    '      sub = {prefix}meta[, {prefix}conf[UI == sub1]$ID, with = FALSE][[1]], \n',
    '      val = score \n',
    '    ) \n',
    '    if (length(input${prefix}comb_sub2) != 0 && \n',
    '        length(input${prefix}comb_sub2) != nlevels(ggData$sub)) \n',
    '      ggData <- ggData[sub %in% input${prefix}comb_sub2] \n',
    '    ggCol  <- strsplit({prefix}conf[UI == input${prefix}comb_grp]$fCL, "\\\\|")[[1]] \n',
    '    names(ggCol) <- levels(ggData$X) \n',
    '    ggLvl  <- levels(ggData$X)[levels(ggData$X) %in% unique(ggData$X)] \n',
    '    ggData$X <- factor(ggData$X, levels = ggLvl) \n',
    '    ggCol  <- ggCol[ggLvl] \n',
    '    inpfsz <- sList[input${prefix}comb_mod_fsz] \n',
    '    if (input${prefix}comb_mod_vln_typ == "violin") {{ \n',
    '      ggOut <- ggplot(ggData, aes(X, val, fill = X)) + geom_violin(scale = "width") \n',
    '    }} else {{ \n',
    '      ggOut <- ggplot(ggData, aes(X, val, fill = X)) + geom_boxplot() \n',
    '    }} \n',
    '    if (input${prefix}comb_mod_vln_pts) \n',
    '      ggOut <- ggOut + geom_jitter(size = input${prefix}comb_mod_siz, shape = 16) \n',
    '    ggOut + \n',
    '      xlab(input${prefix}comb_grp) + ylab("Module Score") + \n',
    '      sctheme(base_size = inpfsz, Xang = 45, XjusH = 1) + \n',
    '      scale_fill_manual("", values = ggCol) + \n',
    '      theme(legend.position = "none") \n',
    '  }}) \n',
    '  output${prefix}comb_mod_vln_oup.ui <- renderUI({{ \n',
    '    plotOutput("{prefix}comb_mod_vln_oup", height = pList2[input${prefix}comb_mod_psz]) \n',
    '  }}) \n',
    '  output${prefix}comb_mod_vln_oup <- renderPlot({{{prefix}comb_mod_vln_oup()}}) \n',
    '  output${prefix}comb_mod_vln_oup.dl <- downloadHandler( \n',
    '    filename = function() {{ \n',
    '      paste0("{prefix}modscore_violin_", input${prefix}comb_grp, \n',
    '             ".", input${prefix}comb_mod_vln_oup.f) \n',
    '    }}, \n',
    '    content = function(file) {{ \n',
    '      ggsav(file, height = input${prefix}comb_mod_vln_oup.h, \n',
    '             width = input${prefix}comb_mod_vln_oup.w, plot = {prefix}comb_mod_vln_oup()) \n',
    '    }} \n',
    '  ) \n',
    '\n',
    '\n',
    '\n'
  )
}

#' Write code for server.R
#'
#' @rdname wrSVpost
#' @export wrSVpost
#'
wrSVpost <- function() {
  glue::glue(
    '}}) \n',
    '\n',
    '\n',
    '\n'
  )
}

